I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 207, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 445, in script
    $ __gl_test()
  File "renpy/common/00start.rpy", line 207, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 445, in script
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 445, in <module>
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 359, in _m1_00gltest__gl_test
    _gl_performance_test()
  File "renpy/common/00gltest.rpy", line 384, in _gl_performance_test
    ui.interact(suppress_underlay=True, suppress_overlay=True)
TypeError: 'tuple' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Program Files\renpy-6.99.8-sdk\renpy\bootstrap.py", line 316, in bootstrap
    renpy.main.main()
  File "C:\Program Files\renpy-6.99.8-sdk\renpy\main.py", line 578, in main
    run(restart)
  File "C:\Program Files\renpy-6.99.8-sdk\renpy\main.py", line 143, in run
    renpy.execution.run_context(True)
  File "C:\Program Files\renpy-6.99.8-sdk\renpy\execution.py", line 908, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 207, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 445, in script
    $ __gl_test()
  File "renpy/common/00start.rpy", line 207, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 445, in script
    $ __gl_test()
  File "C:\Program Files\renpy-6.99.8-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Program Files\renpy-6.99.8-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "renpy/common/00gltest.rpy", line 445, in <module>
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 359, in _m1_00gltest__gl_test
    _gl_performance_test()
  File "renpy/common/00gltest.rpy", line 384, in _gl_performance_test
    ui.interact(suppress_underlay=True, suppress_overlay=True)
  File "C:\Program Files\renpy-6.99.8-sdk\renpy\ui.py", line 297, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Program Files\renpy-6.99.8-sdk\renpy\display\core.py", line 2665, in interact
    self.start()
  File "C:\Program Files\renpy-6.99.8-sdk\renpy\display\core.py", line 1805, in start
    self.set_mode()
  File "C:\Program Files\renpy-6.99.8-sdk\renpy\display\core.py", line 2045, in set_mode
    if draw.set_mode(virtual_size, physical_size, fullscreen):
  File "gldraw.pyx", line 379, in renpy.gl.gldraw.GLDraw.set_mode
TypeError: 'tuple' object is not callable

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Hero's Reward 1.0
Tue Jul 28 15:14:40 2020
